# Generated by Django 3.1.1 on 2020-09-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='Mention',
        ),
        migrations.AlterModelOptions(
            name='mention',
            options={'verbose_name': 'Mention', 'verbose_name_plural': 'Mentions'},
        ),
        migrations.RenameField(
            model_name='mention',
            old_name='sound',
            new_name='tweet',
        ),
    ]
