# Generated by Django 3.1.1 on 2020-10-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200930_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='replied',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='mention',
            name='tweet_id',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='mention',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='mention',
            name='tweet',
            field=models.CharField(max_length=300),
        ),
    ]
