# Generated by Django 3.1.1 on 2020-10-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200930_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='img',
            field=models.URLField(default='No img'),
        ),
    ]
