# Generated by Django 3.1.1 on 2020-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_mention_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='tweet_id',
            field=models.BigIntegerField(default=2),
        ),
    ]
